### ISSUE TITLE
Search only supported emojis

### ISSUE THREAD

**Issue by eteeselink** [nolanlawson/emoji-picker-element#120]
First off, this library is absolutely amazing, I've yet to find an OSS UI component that I feel is as well done (inside and out) as this one. Hats off!

When using the Database to search emojis, I noticed that the results include emojis that the current os/browser does not support. This makes sense, I guess, as the Database is a pure JS thing that doesn't depend on the browser at all, but it does make it hard to use your excellent native-emoji-filtering code in scenarios where you don't want to show the entire picker.

I've been thinking a bit about what approaches there might be that keep with the spirit of your design. One might be totally extracting the emoji support detection and filtering into a third exported class (besides Picker and Database). But that feels a bit over-engineered somehow - especially since it'd need to do all the init and browser setup code that the Picker also does.

A simpler option might be to maybe have the Picker class expose some of the same methods that Database does, eg `getEmojisBySearchQuery` and `getEmojisByGroup`. Then, any user who wants the browser-curated version of the emoji database can just instantiate a Picker and call it from there. But it feels a bit quirky too, with the Picker instance being a DOM node and and these functions influencing the DOM node's behavior whatsoever. What do you think? 

I'd happily provide a PR, as I guess most solutions aren't _hard_ per se. But many solutions would mess up your code in ways you'd likely prefer not to accept, and suppose there's more fun to be had than arguing with contributors about why their code is too shitty to make it in. So I figured I'd ask you for your thoughts first.

**Comment by nolanlawson** [comment]
Thanks for opening this PR. I had thought about this problem but hadn't started on it yet.

> One might be totally extracting the emoji support detection and filtering into a third exported class (besides Picker and Database). 

This was actually the approach I would prefer. In fact it might be best as a totally standalone package, since the problem of "does this OS/browser support this emoji" is a generic problem.

There is already a package called [if-emoji](https://github.com/Dafrok/if-emoji) that attempts to do this. Unfortunately its approach is not as good as emoji-picker-element, which is why I didn't use it.

I don't think the picker should directly expose its feature detection logic. The unfortunate reason is that it's pretty complex, and the current logic only really works for the picker because it has to be done in a very specific way to avoid extra style/layout calculation costs. (You can imagine that laying out emojis on the page and measuring their width/height is a potential performance disaster. Therefore emoji-picker-element is very careful about it.)

If this were a standalone library, though, it would have to do the following:

First, render to canvas to detect emoji rendered in black-and-white:

https://github.com/nolanlawson/emoji-picker-element/blob/7cbd467ce0ae6dc9ba36aa2f48500d526b585712/src/picker/utils/testColorEmojiSupported.js#L29-L32

Second, check that the width is not double-width (using a heuristic, as these numbers are fuzzy on some browsers/platforms):

https://github.com/nolanlawson/emoji-picker-element/blob/7cbd467ce0ae6dc9ba36aa2f48500d526b585712/src/picker/utils/checkZwjSupport.js#L20

Currently emoji-picker-element does the first one in canvas and the second one in DOM (it's just simpler that way, since it's rendering stuff to the DOM anyway, to do the second check in-DOM). But ideally all of this work could be done in pure canvas.

The other option is to just be inefficient about it and render to both canvas and DOM. This is actually what I did in my app, where I basically just copy-pasted some of the logic from emoji-picker-element:

https://github.com/nolanlawson/pinafore/blob/f09e1bd97585acd46310cb4196b5f60d461076a7/src/routes/_utils/testEmojiSupported.js#L10-L17

Maybe this could be extracted into a standalone library?

**Comment by nolanlawson** [comment]
[is-emoji-supported](https://github.com/koala-interactive/is-emoji-supported) looks promising, although I'd need to test it to see if its logic matches emoji-picker-element. Based on the code though it seems like it might.

**Comment by nolanlawson** [comment]
I tested the above library, and it seems to match emoji-picker-element very closely. Also the implementation is pure-canvas, which is great. Performance seems reasonable.

The only difference I observe is that on Windows it considers the flag emojis to be unsupported, whereas emoji-picker-element does not. I think this is up for debate since Windows shows just the two-letter country codes.

I'll add a note to the readme about this. Thanks!

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/emoji-picker-element/commit/1fd4cf0bf87cfe3c26fba5512b49bc5dee750c96

**Comment by eteeselink** [comment]
Nice find! And thanks for taking the time to look into this. I agree that is-emoji-supported seems like a perfectly good solution.
