### ISSUE TITLE
Uncaught TypeErrors

### ISSUE THREAD

**Issue by the-turk** [nolanlawson/emoji-picker-element#166]
Hi,

I've installed the repo using `npm install emoji-picker-element` and imported it via `import 'emoji-picker-element';`. But when I try to use `<emoji-picker></emoji-picker>` in my component, these console errors shows up:

```console
Uncaught TypeError: each_value_2 is undefined
create_each_block_1 picker.js:1045
...
Uncaught TypeError: tabpanelElement is undefined
update picker.js:2402
```

Everything is working fine if I import it as a `<script>` tag instead of using `npm`

```html
<script type="module" src="https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js"></script>
```

I'm on FireFox 89.0.2, haven't tested with other browsers.

**Comment by nolanlawson** [comment]
@the-turk Which bundler are you using? (Webpack/Rollup/Parcel/etc.) Any bundler plugins? Does it repro in Chrome/Safari as well?

I can't reproduce in Firefox 89.0.2 myself, but I'm using Rollup. If I had to guess, I'd say it may be something about your build process, since you're able to use it just fine directly as a `<script>` tag (i.e. no bundler involved). If you have a small Node project to reproduce, that would be very helpful. :slightly_smiling_face:

**Comment by nolanlawson** [comment]
Closing as a stale issue, please reopen if it's still a problem and/or if there is a repro. :slightly_smiling_face:
