### ISSUE TITLE
[Not an issue] Just want to say thank you

### ISSUE THREAD

**Issue by avioli** [nolanlawson/emoji-picker-element#199]
This is not an issue.

Thanks @nolanlawson for this great picker and all the hours you’ve put into it.

In a time of overly huge and complex components, when most of all web-apps on the web are heavy and complex bundled beasts - having a great example how to use modern technology to make a great custom element.

The repository structure is probably the second best thing for me. It shows how to have a comprehensive suite for a modern and not-too-simple custom element. It will be an inspiration for me, when I create custom elements.

(Feel free to close it and sorry for the spam)

**Comment by nolanlawson** [comment]
Thanks a lot! I appreciate seeing issues like this; just makes my day a bit brighter. :slightly_smiling_face: 

In case you're looking for inspiration on your next custom element project, there's one thing I would say: if I could go back in time, I might choose to use Karma instead of Jest for the tests. Jest tests are neat because they run in-Node rather than in-browser, but there are enough differences between a real browser and Jest/JSDom that I'm starting to feel like it's more trouble than it's worth.

But hopefully other than that, the repo is pretty decent to look at. :sweat_smile: Anyway, thanks!
