### ISSUE TITLE
getEmojiByShortcode not working consistently for upside_down

### ISSUE THREAD

**Issue by brianlukoff** [nolanlawson/emoji-picker-element#222]
First, thanks for an absolutely fantastic component -- beautiful work here!

Certain emojis seem to not be consistently found by `getEmojiByShortcode` until the emoji picker is activated. If I open up the emoji picker and then immediately call `getEmojiByShortcode('upside_down')`, it returns the emoji (🙃). But a subsequent identical call to `getEmojiByShortcode('upside_down')` returns `null`. If I reopen the emoji picker then the call works again!

**Comment by nolanlawson** [comment]
@brianlukoff Thanks for the report. Is this only happening for certain emoji? Do you have a test case to repro?

Off the top of my head, I can't imagine why this would be happening. Are you calling `picker.database`, or are you calling the `Database()` constructor explicitly? What do you mean by "until the emoji picker is activated"?

I tried to repro, but could not. Here is a CodePen: https://codepen.io/nolanlawson/pen/mdwEYqo

(Note that in the default emoji set, the shortcode is `upside_down_face`, not `upside_down`.)

**Comment by brianlukoff** [comment]
Thanks for looking into this! 

I'm using `new Database()` along with the polyfill you recommend using FakeIndexedDB (mainly to support users that are in "private mode" in the browser).

What I mean by activating the emoji picker is adding an instance of it to the DOM (I'm putting it in a Bootstrap popover).

I'm having the issue with `upside_down` specifically -- some others have been reported to us, but that's the example we've used to try to reproduce. (I'm using the JoyPixels emoji dataset.) Thanks for setting up the CodePen -- if I change `upside_down_face` to `upside_down` in that CodePen then I'm able to reproduce something similar -- one of the calls to `getEmojiByShortcode` succeeds and the other fails.

**Comment by nolanlawson** [comment]
Hm, when I change the CodePen to use `upside_down`, I get null both times. Here is a fork: https://codepen.io/nolanlawson/pen/PojGJev

Note that `getEmojiByShortcode` is looking for a direct match – it's not a fuzzy search like `getEmojiBySearchQuery`. If I had to guess, I'd say that there is something odd about how you're setting the `dataSource` on the emoji picker – perhaps sometimes you are getting the default emoji set, and sometimes you are getting the JoyPixels one. This could explain why `upside_down` sometimes works and sometimes not.

For instance, this will lead to weird behavior:

```js
const picker = document.createElement('emoji-picker')
document.body.appendChild(picker) // using the default emoji set

setTimeout(() => {
  picker.dataSource = '/something/else.json' // now it's a different data source 5 seconds later
}, 5000)
```

`locale` can also have a strange effect if you're setting that, since the emoji are cached in IndexedDB based on the `locale`. My recommendation is to set the `dataSource`/`locale` as early as possible, e.g. as attributes on the HTML element or when inserting into the DOM (depending on what framework you're using).

**Comment by brianlukoff** [comment]
Sorry about that -- I could have sworn I was seeing the function return an emoji the first time and not the second time in your original CodePen when I changed the code, but I'm now seeing the behavior you describe!

I figured it out. We're using this in two places -- the picker is loaded with the correct data source every time, but we're also manually instantiating a `Database` object for rendering purposes outside of the picker, and that one was not being loaded with the JoyPixels `dataSource`. 

Thanks for your help!
