### ISSUE TITLE
Multiple small squares appear when used under win7

### ISSUE THREAD

**Issue by Alisonispig** [nolanlawson/emoji-picker-element#264]
When I use it in win7, the following problems arise. The author hopes that I can be associated with his issuse, so is there a solution

![image](https://user-images.githubusercontent.com/29892659/154884410-c1e0ae54-1546-4aff-a055-15b1004eaabc.png)

https://github.com/antoine92190/vue-advanced-chat/issues/282  This is the original address

**Comment by nolanlawson** [comment]
Hi, thanks for opening this issue! [Microsoft has ended Windows 7 support in January of 2020](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information). I do not intend to add built-in support for Windows 7, since `emoji-picker-element` relies on the built-in emoji supplied by the OS, and Windows 7 (AIUI) does not have those emoji.

If you absolutely need Windows 7 support, you can look into using Twemoji (see the [Examples section](https://github.com/nolanlawson/emoji-picker-element#examples) of the README). I would recommend _only_ doing this for Windows 7, though, since it adds a non-negligible performance degradation.

**Comment by Alisonispig** [comment]
![image](https://user-images.githubusercontent.com/29892659/155049460-6d8f3911-4a61-4c96-91c3-c2a7c5cb1fc5.png)

In fact, there are still boxes using twemoji. How to remove these boxes? Can you help me?

**Comment by nolanlawson** [comment]
It looks like this is because [Twemoji](https://github.com/twitter/twemoji) only supports emoji v13.1, not v14. I can't think of a great solution off the top of my head. You could host the emoji JSON file yourself and manually remove all emoji from v14. Or use an older version of emoji-picker-element which did not support emoji v14.
