### ISSUE TITLE
`--emoji-font-family` CSS property not working correctly on Windows

### ISSUE THREAD

**Issue by imattferreira** [nolanlawson/emoji-picker-element#396]
Hey, what's up?

Recently, I've started implementing the `emoji-picker-element` for a design system written in `ReactJS`. For a better experience between the platforms that the design-system primarily support (Windows, Android, iOS and macOS, all in your web versions) I decided to use Apple Emojis instead of native emojis.

 To configure the Apple Emojis for the emoji picker, I have using the `--emoji-font-family` CSS property with the value `"Apple Color Emoji"`. But for some reason, in Windows devices are rendered native emojis instead of the Apple Emojis, but I already verified in the DevTools and the property are overriding the default value with the correct.
 
 
![image](https://github.com/nolanlawson/emoji-picker-element/assets/52766091/aabb50ce-0a89-4bfd-895e-d08e958310ac)

 
  In addiction with this setting, I've configured the emoji picker with the `v15` as emoji version, `pt-BR` as i18n and `https://cdn.jsdelivr.net/npm/emoji-picker-element-data@1.6.0/pt/cldr/data.json` as dataSource.
  
  
Here is a [minimal reproduction](https://codesandbox.io/p/sandbox/snowy-sound-5lp3fy) in codesandbox with the way I have using the library.

I appreciate for the help.

**Comment by nolanlawson** [comment]
`--emoji-font-family` is designed for cases where you are bringing your own font file (e.g. your own WOFF2 file). It will not work in situations where you are trying to use the built-in fonts instead, unless those fonts are available cross-platform. `Apple Color Emoji` is only available on Apple devices, not Windows devices.

If you want to use the Apple font everywhere, you would need to find a way to package up the Apple font as a WOFF2 file and include that on your web page (and also get permission from Apple since there are copyright issues involved :slightly_smiling_face:).

For reference, please see [the example](https://nolanlawson.github.io/emoji-picker-element/demos/twemoji-mozilla/index.html) which uses a custom Twemoji WOFF2 font.

**Comment by nolanlawson** [comment]
Closing, please reopen if I misunderstood the question!
