### ISSUE TITLE
Custom emoji category order

### ISSUE THREAD

**Issue by datagutt** [nolanlawson/emoji-picker-element#41]
By default, custom emoji categories are sorted alphabetically. I wish to pin/put certain categories over others.
I don't see a current way to do this, is this something that could be added? Maybe let me provide a custom sort-function?

**Comment by nolanlawson** [comment]
This sounds like a reasonable feature request. I'm kind of wondering how best to implement it, though:

1. Intuitively, an array of strings is the most straightforward, but it may vary based on the `i18n` settings... and yet, I don't really want to put this into the `i18n` object, because it's more about logic than i18n.
2. The custom sorting function is a bit overkill if you just want to specify an array of strings, but it is the most flexible, and it can allow folks to specify different behavior for different i18n objects.

I'm more partial to # 2 (as you suggest). Maybe `categorySorting` can be a custom function you can pass in to the `Picker` constructor (or at runtime).

**Comment by datagutt** [comment]
I was previously using emoji-mart, which had a solution like 1. Either of these options are fine for my use case, but the categorySorting-option seems like the ideal solution since it will allow for maximum flexibility.
