### ISSUE TITLE
major performance issues when many custom emojis are available

### ISSUE THREAD

**Issue by easrng** [nolanlawson/emoji-picker-element#444]
I'm on a fedi instance with 19k custom emojis (see https://emojos.in/pleroma.envs.net) and when I open the emoji picker in Enafore (my fork of Pinafore), which uses emoji-picker-element, the page freezes for like a full second at least and overall performance stutters for a while after that. Here's a minimal reproduction: https://codepen.io/easrng/full/dyBwYZq

**Comment by nolanlawson** [comment]
Thanks for reporting, I can repro. The main issue here is that there are almost 20k custom emoji, which end up creating 40,139 DOM nodes in the emoji tab panel!

![Screenshot from 2024-09-05 18-30-29](https://github.com/user-attachments/assets/965ca639-2f7f-4245-880e-a11aed8c9807)

I admit that I just did not really think anyone would have so many custom emoji... the design of `emoji-picker-element` was to be as simple as possible, which is why it just injects regular `<button>`s with `<img>`s inside of them, rather than using a fancy virtual list approach (which is probably what you'd need to make this scenario performance). Either that, or we'd need a way to have different tab buttons for each custom emoji (so that only a small group of custom emoji is shown at once).

There is also a non-negligible amount of time spent in the framework code. I could probably look into optimizing that, but I think there is no way that 40k DOM nodes are ever going to be performant. You can tell by just how much time the browser is spending merely Painting (green bars).

![Screenshot from 2024-09-05 18-33-39](https://github.com/user-attachments/assets/69661c80-9428-44ce-93b9-9b10dbe0b56b)

**Comment by nolanlawson** [comment]
Another possibility: use an `IntersectionObserver` to only show the `<img>` if it's visible... would at least cut down the # of DOM nodes by ~50%.

**Comment by nolanlawson** [comment]
I also note that every one of these emojis is marked `visible_in_picker = true`.

**Comment by easrng** [comment]
Fortunately "known grid of fixed size items" is just about the easiest thing to virtualize out there :P

**Comment by nolanlawson** [comment]
IME the trickiest part is actually accessibility. But virtualization is certainly something to consider.

**Comment by nolanlawson** [comment]
I'm going to consider this closed thanks to recent perf improvements (#445 #446 #448 #450). In Chrome and Firefox at least it's >50% faster, and in Chrome your repro loads in 1.3s rather than 3s for me.

It's still not an optimal solution – that would be full-on virtualization. But this is a lightweight solution that trades some perf for simplicity of implementation. Also 20k custom emojis is pretty unusual – I checked, and `mastodon.social` has 135, `mastodon.cloud` has 295, and `mas.to` has 1033.

Thanks for reporting!

**Comment by easrng** [comment]
You'd be suprised, look at https://emotes.cc/toplist
I am on the one with the most right now, but it's not the only one with that order of magnitude

**Comment by easrng** [comment]
and tysm for fixing it, it's so much more usable now!!
