### ISSUE TITLE
Add a custom category with native emojis

### ISSUE THREAD

**Issue by espen** [nolanlawson/emoji-picker-element#477]
I want to create a custom category with native emojis. Is it possible to define custom emojis without a url, so get the emoji using an existing shortcode/unicode? Or in some other way add native emojis to a custom category? Perhaps use multiple data sources? I want to use the standard data source, but I can provide a second data source for only the emojis in my custom category (this cannot be precompiled as each user will have their own unique set of emojis for this category).

**Comment by nolanlawson** [comment]
Sorry, but the emoji picker is not really well-designed right now for what you're asking for. There are a lot of hard-coded assumptions that the custom tabset only contains "custom" emoji, and that "custom" emoji means non-native. I'm also not particularly interested in adding this functionality, since it adds a lot of complexity for one particular use case. I'd recommend forking this project to achieve what you want.

**Comment by espen** [comment]
Sure, I understand. Thanks for the answer. But will a custom data source solve this? Using data that has an additional category, or are the standard categories fixed? Then I can just add a list of the native emojis in a newly name category in addition to the standard categories. If so, can I manually load an additional data source?

**Comment by nolanlawson** [comment]
You cannot solve this with a data source alone. You would need to fork the code sadly. The categories (are we talking about the same thing? the tabs, not the custom emoji subcategories?) are fixed:

https://github.com/nolanlawson/emoji-picker-element/blob/919c1f3fbd9f1ac8531bb4c5e16dfe7f308ccc5b/src/picker/groups.js#L2-L12

**Comment by espen** [comment]
Yes, these groups are what I refer to as categories. Ok, by looking at this I understand what you mean. Thanks for the explanation.
