### ISSUE TITLE
Add support for icon-fonts for custom emojis

### ISSUE THREAD

**Issue by ErikMichelson** [nolanlawson/emoji-picker-element#55]
Currently, custom emojis are limited to single image files. It would be great though if one can use custom non-image "emojis". This is especially useful if you want to support icons from icon-fonts such as FontAwesome or material-icons.

My idea how to realize this looks as following:
 - Custom emojis get a new optional property `html`
 - If the `html`-property is not set, the emoji will be rendered as an image with the defined source (`url`)
 - If the `html`-property is set, the `url`-property will be ignored and instead the `html` code will be rendered instead of the image

This allows setting e.g. `<i class="fa fa-home"></i>` as `html`.

If such an approach sounds reasonable, I'd like to help implement it.

---

The background for this issue: I'm one of the devs of @codimd. We're currently re-building our app and want to include your emoji-picker as it performs quite well. As we allow users to insert ForkAwesome icons, we wanted to integrate that into the picker without the need for single image files.

**Comment by nolanlawson** [comment]
Thanks for opening the issue. I think it's an interesting idea to allow for generic custom HTML elements, but I have some concerns:

1. In general, I see icon fonts as a legacy format for a time when browsers didn't handle SVG very well. Even in the case of FontAwesome/ForkAwesome, there are [SVG versions that can be used](https://www.npmjs.com/package/font-awesome-svg-png). This has several benefits, such as not using fonts for something other than their intended purpose, being able to have separate SVG files or simply setting the url to `/bundle.svg#icon-name` to do selective bundling with `<symbol>`s, being able to animate the SVG icons, etc.
2. Allowing people to insert arbitrary HTML here opens us up to security vulnerabilities in the case of unsafe user-supplied HTML (e.g. XSS attacks inserting a `<script>`). Also there is the performance hit that Svelte will call `element.innerHTML = string` rather than using more efficient DOM APIs.

So overall I would wonder – is it possible on your side of things to switch from icon fonts to SVG icons? You can see an example of this on https://nolanlawson.github.io/emoji-picker-element/ – it loads individual SVG files, but it could just as easily bundle them into a single file and use URLs like `/bundle.svg#icon-name`, which is fairly equivalent to icon fonts, with other advantages mentioned above.

**Comment by ErikMichelson** [comment]
Okay, thanks for the details. I guess we're looking into a svg-bundle solution for now.

**Comment by nolanlawson** [comment]
Hmm, interestingly I just looked into this, and it turns out [you can't use SVG symbols as a CSS `background-image`](https://stackoverflow.com/questions/28477256/setting-a-css-background-image-to-an-inline-svg-symbol). So actually my proposed solution will not work (although individual SVG files will).

So it looks like I should probably support `<svg>` with `<use>` as an optional way to include custom icons. I also realize belatedly that this would be the only way to make the icons animatable (not with `background-image`). So it looks like there is some more work to be done here to support this use case.

**Comment by nolanlawson** [comment]
I'm looking into the "arbitrary HTML" solution, as a way of solving both SVG `<symbol>`s and icon fonts (or whatever people want to use). But there are some issues:

- you can't style it, because it's shadow DOM, not light DOM. so the temptation is to just put in repeated `style="..."`
- ideally the `custom-emoji` class would apply to the top-level HTML element, but there's no easy way to tell Svelte to use arbitrary HTML but then modify the HTML somehow (without regex replacement or similar)
- the other problems noted above

So I'm still noodling on this. I understand the use case, trying to figure out how best to address it.

**Comment by nolanlawson** [comment]
Thought about this a bit more. For an SVG with `<symbol>`s, this can be solved by using blob URLs, data URLs, or service worker URL overrides.

Also arguably there is an advantage to having separate `<img>`s pointing to separate resources, because we now have lazy image loading.

I'm going to consider this closed for now since there are quite a few workarounds (in your case, separate SVG files seems like the simplest), and I'm inclined to keep the implementation small and simple. But I'm open to other options if there's a good proposal.
